### ISSUE TITLE
IOS: ERROR ReferenceError: Can't find variable: ToastStyle

### ISSUE THREAD

**Issue by bellalMohamed** [triniwiz/nativescript-toasty#35]
Plugin is not working on IOS and throwing the following error:
```
ERROR ReferenceError: Can't find variable: ToastStyle
```
---------
I did debug the issue and found out that there's a folder on the package called "typings" that is not installed with the package, which includes the file ```objc!Toast_Swift.d.ts``` that has the declaration for ```ToastStyle```

**Comment by JNicolasW** [comment]
I have the same issue but, i use the same code, assets and everything in two projects, but the issue only occurs on one, not both. Any idea why? Or what should I look for?

**Comment by triniwiz** [comment]
Can you try the demo or nuking the project ?

**Comment by bellalMohamed** [comment]
Performing ```tns update``` and updating IOS version from ```"version": "6.2.0"``` to ```"version": "6.3.0"``` fixed this issue, also It fixes some similar issue with packages like ```nativescript-cfalert-dialog```

**Comment by jpw9** [comment]
I have the same issue.  Anyone managed to solve it?

**Comment by bellalMohamed** [comment]
> I have the same issue.  Anyone managed to solve it?

Running ```tns update``` should fix it

**Comment by maxfriedmann** [comment]
Still doesn't work with ns 8.x. Just add it to a fresh app and run iOS!
